name: Run TPA Motivation Bot

on:
  schedule:
    - cron: '0 23 * * 0-4'  # 06:00 GMT+8
  workflow_dispatch:

jobs:
  motivation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Motivation Tip
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: |
        python -m src.bot motivation
