name: Run TPA Auto-Post Bot

on:
  schedule:
    # Run calendar job at 00:01 UTC every day
    - cron: '1 0 * * *'
    # Run motivation job at 07:00 UTC every day
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Determine job type
      id: job-type
      run: |
        hour=$(date +%H)
        minute=$(date +%M)
        if [ "$hour" = "00" ] && [ "$minute" = "01" ]; then
          echo "type=calendar" >> $GITHUB_OUTPUT
        elif [ "$hour" = "07" ] && [ "$minute" = "00" ]; then
          echo "type=motivation" >> $GITHUB_OUTPUT
        else
          # For manual runs, default to both
          echo "type=both" >> $GITHUB_OUTPUT
        fi

    - name: Run calendar job
      if: steps.job-type.outputs.type == 'calendar' || steps.job-type.outputs.type == 'both'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: |
        python -m src.bot calendar

    - name: Run motivation job
      if: steps.job-type.outputs.type == 'motivation' || steps.job-type.outputs.type == 'both'
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: |
        python -m src.bot motivation 